import { Regulator } from './types/regulator';

export const regulators: Regulator[] = [
  {
    id: 1,
    name: 'John Smith',
    email: 'john.smith@regulator.gov',
    regCountry: 'USA',
    regState: 'Los Angeles',
    region: 'North America',
    status: 'Active',
    joinedDate: '2024-01-10',
    phone: '+1 (555) 123-4567',
    department: 'Financial Oversight',
    title: 'Senior Regulatory Officer',
  },
  {
    id: 2,
    name: 'Sarah Johnson',
    email: 'sarah.johnson@regulator.gov',
    region: 'Europe',
    regCountry: 'Spain',
    regState: 'Barcelona',
    status: 'Active',
    joinedDate: '2024-02-15',
    phone: '+44 20 7946 0958',
    department: 'Compliance Monitoring',
    title: 'Lead Compliance Analyst',
  },
  {
    id: 3,
    name: 'Michael Chen',
    email: 'michael.chen@regulator.gov',
    region: 'London',
    regCountry: 'England',
    regState: 'London',
    status: 'Inactive',
    joinedDate: '2024-01-20',
    phone: '+65 6123 4567',
    department: 'Risk Assessment',
    title: 'Risk Assessment Specialist',
  },
];
